name: busybeaver
favicon: null
layout_spectrum: 0.15299
typography_spectrum: 0.18255
title: Busy Beaver
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#36abdf'
    - '#9bd1ee'
    - '#59bae4'
    - '#bee4f4'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
